Add legend to html reports
gardener/diki pull request #270
Opened 2024-07-05 13:51 UTC by AleksandarSavchev

**What this PR does / why we need it**:
This PR adds a legend to all `html` reports which contains the meanings of rule check statuses.

**Which issue(s) this PR fixes**:
Fixes #269 

**Special notes for your reviewer**:

**Release note**:

```feature user
A legend has been added to `html` reports that explains rule statuses.
```

2024-07-08 07:47 UTC, dimityrmirchev requested changes
Can you please upload an image of how this is going to look in the report?

2024-07-08 07:47 UTC, dimityrmirchev commented on pkg/rule/rule.go
> +func GetStatusMeaning(status Status) string {
```suggestion
func StatusDescription(status Status) string {
```

2024-07-08 07:47 UTC, dimityrmirchev commented on pkg/rule/rule.go
> +func GetStatusMeaning(status Status) string {
Let's rename meaning to description everywhere

2024-07-08 07:47 UTC, dimityrmirchev commented on pkg/rule/rule.go
> +// GetStatusMeaning returns the meaning of a given Status string
```suggestion
// GetStatusMeaning returns the meaning of a given [Status] string.
```

2024-07-08 08:16 UTC, AleksandarSavchev commented
> Can you please upload an image of how this is going to look in the report?

<img width="1156" alt="image" src="https://github.com/gardener/diki/assets/57963548/8dbeac50-f5ab-4332-97c1-5bf1a5d3cb92">


<img width="1156" alt="image" src="https://github.com/gardener/diki/assets/57963548/ec3b35c5-e553-4637-b746-889beaff518d">

2024-07-15 13:58 UTC, dimityrmirchev commented on pkg/rule/rule.go
> +		return "Ran rule check has encountered a condition where it cannot be determined if the check is Fulfilled or not."
```suggestion
		return "The rule check has encountered an ambiguous condition or configuration preventing the ability to determine if the check is fulfilled or not."
```

2024-07-16 06:43 UTC, dimityrmirchev approved these changes
/lgtm

2024-07-16 07:03 UTC, merged