Consistently use namespaceMatchLabels across rules
gardener/diki pull request #316
Opened 2024-10-11 05:39 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR refactors the accepted pod structs implemented for rules #242414 and #242415 by aggregating the label matching options into a singular shared structure.
The accepted pod struct for #242417 is refactored to utilize the new structure and now can add exemptions from the ruleset checks by matching namespaces by labels.
The accepted pod struct for #242383 is refactored as well to use namespace labels for matching its rule exemptions.

**Which issue(s) this PR fixes**:
Fixes #286

**Special notes for your reviewer**:

**Release note**:

```feature user
The implementation is a breaking change that will require changes to the .yaml configuration files used by the end users for listing their accepted pods.
```

2024-10-11 09:31 UTC, AleksandarSavchev requested changes
Please adapt the example `managedk8s` diki config file to use the new `namespaceMatchLabels` option:
https://github.com/gardener/diki/blob/1529d1bbbc1a195da4adac46561b427c5a65145d/example/config/managedk8s.yaml#L29-L33
https://github.com/gardener/diki/blob/1529d1bbbc1a195da4adac46561b427c5a65145d/example/config/managedk8s.yaml#L105-L108
Also write a comment describing which namespaces can be selected. Example for `242383`:
```
# Only namespaces in ["default", "kube-public", "kube-node-lease"]
# can be selected with namespaceMatchLabels
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383.go
>  	if err != nil {
```suggestion
	notDikiPodReq, err := labels.NewRequirement(pod.LabelComplianceRoleKey, selection.NotEquals, []string{pod.LabelComplianceRolePrivPod})
	if err != nil {
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383.go
>  		if err != nil {
```suggestion
	for _, namespace := range systemNamespaces {
		partialMetadata, err := kubeutils.GetAllObjectsMetadata(ctx, r.Client, namespace, selector, 300)
		if err != nil {
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383.go
>  			target := rule.NewTarget("name", p.Name, "namespace", p.Namespace, "kind", p.Kind)
```suggestion
		for _, p := range partialMetadata {
			target := rule.NewTarget("name", p.Name, "namespace", p.Namespace, "kind", p.Kind)
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383_test.go
>  var _ = Describe("#242383", func() {
```suggestion

var _ = Describe("#242383", func() {
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383_test.go
>  		kubernetesService := &corev1.Service{
```suggestion
	It("should return passed checkResult when no user resources are present in system namespaces", func() {
		kubernetesService := &corev1.Service{
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383_test.go
>  		pod := plainPod.DeepCopy()
```suggestion
	It("should return correct checkResult when different resources are present", func() {
		pod := plainPod.DeepCopy()
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242383_test.go
>  	})
```suggestion
		Expect(ruleResult.CheckResults).To(ConsistOf(expectedCheckResults))
	})
```

2024-10-11 09:31 UTC, AleksandarSavchev commented on pkg/shared/ruleset/disak8sstig/rules/242417.go
>  	if err != nil {
```suggestion
	notDikiPodReq, err := labels.NewRequirement(pod.LabelComplianceRoleKey, selection.NotEquals, []string{pod.LabelComplianceRolePrivPod})
	if err != nil {
```

2024-10-11 11:56 UTC, georgibaltiev commented
I've added 3 new commits that may resolve the issues. The unnecessary newlines are removed, and the structs are renamed accordingly.

2024-10-14 08:56 UTC, dimityrmirchev requested changes

2024-10-14 08:56 UTC, dimityrmirchev commented on example/config/managedk8s.yaml
> +    #       # only namespaces in ["default", "kube-public", "kube-node-lease" can be selected with namespaceMatchLabels
```suggestion
    #       # only namespaces in ["default", "kube-public", "kube-node-lease"] are meaningful to be selected with namespaceMatchLabels
             # since the rule does not perform checks on objects in namespaces different from the listed above
```

2024-10-14 08:56 UTC, dimityrmirchev commented on example/config/managedk8s.yaml
> +    #       # only pods in namespaces ["kube-system", "kube-public", "kube-node-lease"] can be selected with namespaceMatchLabels
Same as above

2024-10-14 08:56 UTC, dimityrmirchev commented on example/guides/partial-disa-k8s-stig-shoot.yaml
> +    - ruleID: "242449" 
```suggestion
    - ruleID: "242449"
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/provider/gardener/ruleset/disak8sstig/v1r11_ruleset.go
> +						PodSelector: option.PodSelector{PodMatchLabels: map[string]string{
```suggestion
						PodSelector: option.PodSelector{
						PodMatchLabels: map[string]string{
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/provider/gardener/ruleset/disak8sstig/v2r1_ruleset.go
> +						PodSelector: option.PodSelector{PodMatchLabels: map[string]string{
```suggestion
						PodSelector: option.PodSelector{
						PodMatchLabels: map[string]string{
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/option/options.go
> +		rootPath = field.NewPath("acceptedPods")
It is not necessary that the rootPath is "acceptedPods". This struct can be reused in different places. The field path should be passed as parameter. For now lets use an empty root path. We can revisit the validation of different options in another PR.
```suggestion
		rootPath = field.NewPath("")
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/rules/242383.go
> +type ResourceSelector struct {
Let's rename this to ObjectSelector but leave the exposed API using the "acceptedResources" naming since we do not want to make another breaking change
```suggestion
type ObjectSelector struct {
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/rules/242383.go
> +		return rule.SingleCheckResult(r, rule.ErroredCheckResult(err.Error(), rule.NewTarget("", ""))), nil
```suggestion
		return rule.SingleCheckResult(r, rule.ErroredCheckResult(err.Error(), rule.NewTarget())), nil
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/rules/242417.go
> +		return rule.SingleCheckResult(r, rule.ErroredCheckResult(err.Error(), rule.NewTarget("", ""))), nil
```suggestion
		return rule.SingleCheckResult(r, rule.ErroredCheckResult(err.Error(), rule.NewTarget()), nil
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/rules/242383.go
> +				NamespaceMatchLabels: allNamespaces["default"].Labels,
Let's match the `default` namespace by the metadata name label similarly to how we match other namespaces. It would be better to keep this consistent since it will be easier for developers to search similar usages through the code.

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/option/options.go
>  // AcceptedPods242415 contains option specifications for appected pods
```suggestion
// AcceptedPods242415 contains option specifications for accepted pods
```

2024-10-14 08:56 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/option/options.go
>  // AcceptedPods242414 contains option specifications for appected pods
```suggestion
// AcceptedPods242414 contains option specifications for accepted pods
```

2024-10-14 12:54 UTC, georgibaltiev commented on pkg/shared/ruleset/disak8sstig/option/options.go
> +		rootPath = field.NewPath("acceptedPods")
Okay, I will refactor the test cases to comply with the empty initialization.

2024-10-15 04:56 UTC, dimityrmirchev requested changes

2024-10-15 04:56 UTC, dimityrmirchev commented on example/config/managedk8s.yaml
> +    #          kubernetes.io/metadata.name: default
You have an extra whitespace here.
```suggestion
    #         kubernetes.io/metadata.name: default
```

2024-10-15 05:11 UTC, dimityrmirchev approved these changes
/lgtm

2024-10-15 06:05 UTC, AleksandarSavchev approved these changes
/lgtm

2024-10-15 06:05 UTC, merged