Image id parsing bug fix
gardener/diki pull request #321
Opened 2024-10-17 12:48 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR refactors the parsing of image names in all 3 implementations of DISA rule 242442. The strings split functions are replaced by an regex parsing function imported from the package k8s.io/kubernetes/pkg/util/parsers. An additional test to replicate the scenario that provoked the issue has been added as well.

**Which issue(s) this PR fixes**:
Fixes #302

**Special notes for your reviewer**:

**Release note**:

```feature user
Containers running images pulled from a local registry identified as localhost:port can now be correctly evaluated by DISA rule 242442.
```

2024-10-17 14:51 UTC, AleksandarSavchev requested changes
Looks good overall, just a few nits.

2024-10-17 14:51 UTC, AleksandarSavchev commented on pkg/provider/gardener/ruleset/disak8sstig/rules/242442.go
> +					checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), rule.NewTarget("cluster", cluster, "pod", pod.Name, "container", container.Name, "imageRef", imageRef)))
```suggestion
					checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), rule.NewTarget("imageRef", imageRef)))
```
Nit: No need to be too specific here as we should never enter this `if` clause. If we reach this code it is more likely an error in `ParseNormalizedNamed` and we would only care about the `imageRef` it caused it.

2024-10-17 14:51 UTC, AleksandarSavchev commented on pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442.go
> +				checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), rule.NewTarget("name", pod.Name, "container", container.Name, "imageRef", imageRef)))
```suggestion
				checkResults = append(checkResults, rule.ErroredCheckResult(err.Error(), rule.NewTarget("imageRef", imageRef)))
```

2024-10-17 14:51 UTC, AleksandarSavchev commented on pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
> +	It("should return correct results when an image uses more than 1 version #2", func() {
```suggestion
	It("should return correct results when images are local", func() {
```
Let's choose a more specific

2024-10-17 14:51 UTC, AleksandarSavchev commented on pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442_test.go
> +	It("should return correct results when an image uses more than 1 version #2", func() {
```suggestion
	It("should return correct results when images are local", func() {
```

2024-10-17 14:51 UTC, AleksandarSavchev commented on pkg/provider/virtualgarden/ruleset/disak8sstig/rules/242442_test.go
> +	It("should return correct results when an image uses more than 1 version #2", func() {
```suggestion
	It("should return correct results when images are local", func() {
```

2024-10-17 14:51 UTC, AleksandarSavchev commented on pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
> +		pod1.Status.ContainerStatuses[2].ImageID = "localhost:7777/image-two@sha256:" + digest3
```suggestion
		pod1.Status.ContainerStatuses[0].ImageID = "localhost:7777/image1@sha256:" + digest1
		pod1.Status.ContainerStatuses[1].ImageID = "localhost:7777/image1@sha256:" + digest2
		pod1.Status.ContainerStatuses[2].ImageID = "localhost:7777/image2@sha256:" + digest3
```
Nit: We should use either `image[1-9]{1}` or `image-[a-z]+` approach for all cases in out unit tests. I prefer `image[1-9]{1}` but I would be ok if you change them all to `image-[a-z]+` as well.

2024-10-17 15:06 UTC, georgibaltiev commented on pkg/provider/gardener/ruleset/disak8sstig/rules/242442_test.go
> +		pod1.Status.ContainerStatuses[2].ImageID = "localhost:7777/image-two@sha256:" + digest3
The regex will not accept any numbers in the repo/name part of the ImageID. I will use dashes and letters instead

2024-10-18 06:20 UTC, AleksandarSavchev reviewed
Thanks!
/lgtm

2024-10-18 06:27 UTC, dimityrmirchev requested changes
Thanks! Two requests that need to be applied in several places. The rest looks good.

2024-10-18 06:27 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442.go
> +	dockerref "github.com/distribution/reference"
```suggestion
	imageref "github.com/distribution/reference"
```

2024-10-18 06:27 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/disak8sstig/rules/242442_test.go
> +	It("should return correct results when images are local", func() {
```suggestion
	It("should return correct results when image repository includes port number", func() {
```

2024-10-18 06:56 UTC, AleksandarSavchev approved these changes

2024-10-18 07:13 UTC, dimityrmirchev approved these changes
/lgtm

2024-10-18 07:15 UTC, merged