Add Rule 2000 to the Security Hardened Shoot Cluster Ruleset
gardener/diki pull request #362
Opened 2024-11-18 09:48 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR is an implementation of the Rule 2000 of the Security Hardened Shoot Cluster Ruleset. It retrieves metadata about the shoot cluster and evaluates the EnableAnonymousAuthentication flag (if present) of the Kube API Server component.

**Which issue(s) this PR fixes**:
Part of #304 

**Special notes for your reviewer**:

**Release note**:

```feature user
Implementation for rule `2000` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```

2024-11-18 10:37 UTC, AleksandarSavchev requested changes
Looks good, just 2 changes to test names.

2024-11-18 10:37 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000_test.go
> +		Entry("should warn when kube-apiserver configuration is not set",
```suggestion
		Entry("should pass when kube-apiserver configuration is not set",
```

2024-11-18 10:37 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000_test.go
> +		Entry("should warn when anonymous authentication is not set",
```suggestion
		Entry("should pass when anonymous authentication is not set",
```

2024-11-18 12:30 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000_test.go
> +	DescribeTable("Run cases", func(updateFn func(), expectedCheckResults []rule.CheckResult) {
```suggestion
	DescribeTable("Run cases", func(updateFn func(), expectedCheckResult rule.CheckResult) {
```
Last comment, no need for `expectedCheckResults` to be a slice when the function can only return a single `rule.CheckResult`

2024-11-18 12:38 UTC, AleksandarSavchev approved these changes
/lgtm

2024-11-18 19:41 UTC, dimityrmirchev requested changes
Just a single wording change request.

2024-11-18 19:41 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2000.go
> +		return rule.Result(r, rule.PassedCheckResult("Anonymous authentication is disabled on the kube-apiserver.", rule.NewTarget())), nil
```suggestion
	case *shoot.Spec.Kubernetes.KubeAPIServer.EnableAnonymousAuthentication:
		return rule.Result(r, rule.FailedCheckResult("Anonymous authentication is enabled for the kube-apiserver.", rule.NewTarget())), nil
	default:
		return rule.Result(r, rule.PassedCheckResult("Anonymous authentication is disabled for the kube-apiserver.", rule.NewTarget())), nil
```

2024-11-19 08:06 UTC, dimityrmirchev approved these changes
/lgtm

2024-11-19 08:06 UTC, merged