[Security Hardened Shoot Cluster] Rule 2004 Implementation
gardener/diki pull request #365
Opened 2024-11-19 09:22 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR is an implementation of Rule 2004 of the Security Hardened Shoot Cluster Ruleset. It evaluates the admission plugins of the shoot's kube-apiserver by checking if the ValidatingAdmissionWebhook is enabled (explicitly or by default).

**Which issue(s) this PR fixes**:
Part of #304 

**Special notes for your reviewer**:

**Release note**:

```feature user
Implementation for rule `2004` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```

2024-11-19 09:55 UTC, AleksandarSavchev requested changes
Thanks!

2024-11-19 09:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +		return rule.Result(r, rule.PassedCheckResult("The validating admission webhook is not disabled.", rule.NewTarget())), nil
```suggestion
		return rule.Result(r, rule.PassedCheckResult("ValidatingAdmissionWebhook admission plugin is not disabled.", rule.NewTarget())), nil
```

2024-11-19 09:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	return rule.Result(r, rule.FailedCheckResult("The validating admission webhook is disabled.", rule.NewTarget())), nil
```suggestion
	var admissionPlugins = shoot.Spec.Kubernetes.KubeAPIServer.AdmissionPlugins
	targetPluginIdx := slices.IndexFunc(admissionPlugins, func(plugin gardencorev1beta1.AdmissionPlugin) bool {
		return plugin.Name == "ValidatingAdmissionWebhook"
	})

	if targetPluginIdx < 0 || admissionPlugins[targetPluginIdx].Disabled == nil {
		return rule.Result(r, rule.PassedCheckResult("ValidatingAdmissionWebhook admission plugin is not disabled.", rule.NewTarget())), nil
	}
	if !*admissionPlugins[targetPluginIdx].Disabled {
		return rule.Result(r, rule.PassedCheckResult("ValidatingAdmissionWebhook admission plugin is enabled.", rule.NewTarget())), nil
	}
	return rule.Result(r, rule.FailedCheckResult("ValidatingAdmissionWebhook admission plugin is disabled.", rule.NewTarget())), nil
```

Update message and merge 2 `if`s

2024-11-19 09:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004_test.go
> +		Entry("should pass when the kube-apiserver's validating admission webhook is not set",
```suggestion
		Entry("should pass when the kube-apiserver's ValidatingAdmissionWebhook admission plugin is not set",
```

2024-11-19 09:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004_test.go
> +		Entry("should pass when the kube-apiserver's validating admission webhook is enabled explicitly",
```suggestion
		Entry("should pass when the kube-apiserver's ValidatingAdmissionWebhook admission plugin is enabled explicitly",
```

2024-11-19 09:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004_test.go
> +		Entry("should fail when the kube-apiserver's validating admission webhook is enabled explicitly",
```suggestion
		Entry("should fail when the kube-apiserver's ValidatingAdmissionWebhook admission plugin is enabled explicitly",
```

2024-11-19 09:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004_test.go
> +		Entry("should pass when the kube-apiserver's admission plugins are set by default",
```suggestion
		Entry("should pass when the kube-apiserver's ValidatingAdmissionWebhook admission plugin is set by default",
```

2024-11-19 15:39 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	})
This finds the index of the first instance of a plugin with name `ValidatingAdmissionWebhook`. What would happen if the first instance `ValidatingAdmissionWebhook` is enabled, but there is a second instance which is disabled?

2024-11-19 16:43 UTC, georgibaltiev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	})
I am not sure how this configuration should be interpreted (if it's possible). Is it considered a failure because of the disabling instance, or is it a warning due to the ambiguity?

2024-11-21 06:32 UTC, georgibaltiev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	})
For a future reference, The ValidatingAdmissionWebhook is always required by Kubernetes to be enabled, therefore this check is expected to always result in a pass. There isn't a known way to manually disable this admission plugin at the time of this message.

2024-11-21 07:18 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	})
Thanks, can you add a comment in the rule itself that it is not currently possible to disable the plugin. It can be places before the `IndexFunc`s

2024-11-21 07:19 UTC, AleksandarSavchev requested changes
Thanks only this small change, and the added comment and we should be good

2024-11-21 07:19 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	return rule.Result(r, rule.PassedCheckResult("The ValidatingAdmissionWebhook admission plugin is not disabled.", rule.NewTarget())), nil
```suggestion

	enabledIdx := slices.IndexFunc(admissionPlugins, func(plugin gardencorev1beta1.AdmissionPlugin) bool {
		return plugin.Name == "ValidatingAdmissionWebhook" && plugin.Disabled != nil && !*plugin.Disabled
	})
	disabledIdx := slices.IndexFunc(admissionPlugins, func(plugin gardencorev1beta1.AdmissionPlugin) bool {
		return plugin.Name == "ValidatingAdmissionWebhook" && plugin.Disabled != nil && *plugin.Disabled
	})

	if disabledIdx >= 0 {
		return rule.Result(r, rule.FailedCheckResult("The ValidatingAdmissionWebhook admission plugin is disabled.", rule.NewTarget())), nil
	}
	if enabledIdx >= 0 {
		return rule.Result(r, rule.PassedCheckResult("The ValidatingAdmissionWebhook admission plugin is enabled.", rule.NewTarget())), nil
	}

	return rule.Result(r, rule.PassedCheckResult("The ValidatingAdmissionWebhook admission plugin is not disabled.", rule.NewTarget())), nil
```

2024-11-21 07:55 UTC, AleksandarSavchev requested changes

2024-11-21 07:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	// Therefore, this rule check is always expected to pass.
```suggestion
	// The ValidatingadmissionWebhook is required to be enabled by Gardener. ref: https://github.com/gardener/gardener/blob/834a3476ed4343225690cd0eaca32e03ab5b84f5/pkg/utils/validation/admissionplugins/admissionplugins.go#L71
	// Therefore, this rule check is always expected to pass.
```

2024-11-21 07:55 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	if disabledIdx >= 0 {
```suggestion
	})

	if disabledIdx >= 0 {
```

2024-11-21 09:06 UTC, AleksandarSavchev submitted a review, later dismissed
/lgtm

2024-11-21 10:58 UTC, dimityrmirchev requested changes
One code simplification

2024-11-21 10:58 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2004.go
> +	return rule.Result(r, rule.PassedCheckResult("The ValidatingAdmissionWebhook admission plugin is not disabled.", rule.NewTarget())), nil
```suggestion
	if slices.ContainsFunc(admissionPlugins, func(plugin gardencorev1beta1.AdmissionPlugin) bool {
		return plugin.Name == "ValidatingAdmissionWebhook" && plugin.Disabled != nil && *plugin.Disabled
	}) {
		return rule.Result(r, rule.FailedCheckResult("The ValidatingAdmissionWebhook admission plugin is disabled.", rule.NewTarget())), nil
	}

	if slices.ContainsFunc(admissionPlugins, func(plugin gardencorev1beta1.AdmissionPlugin) bool {
		return plugin.Name == "ValidatingAdmissionWebhook" && plugin.Disabled != nil && !*plugin.Disabled
	}) {
		return rule.Result(r, rule.PassedCheckResult("The ValidatingAdmissionWebhook admission plugin is enabled.", rule.NewTarget())), nil
	}

	return rule.Result(r, rule.PassedCheckResult("The ValidatingAdmissionWebhook admission plugin is not disabled.", rule.NewTarget())), nil
```

2024-11-21 12:43 UTC, dimityrmirchev approved these changes
/lgtm

2024-11-21 13:06 UTC, merged