[Security Hardened Shoot Cluster] Rule 2006 Implementation
gardener/diki pull request #366
Opened 2024-11-19 16:40 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR implements Rule 2006 for the Security Hardened Shoot Cluster Ruleset. It evaluates the EnableStaticTokenKubeconfig and the Kubernetes version in the Shoot Spec.

**Which issue(s) this PR fixes**:
Part of #304 

**Special notes for your reviewer**:

**Release note**:

```feature user
Implementation for rule `2006` from the `security-hardened-shoot-cluster` ruleset for provider `garden`.
```

2024-11-20 14:07 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006.go
> +	}
After checking the new changes can we have the message for the default case be the same as here:
```
Static token kubeconfig is not enabled for the shoot.
```
In the other implemented rules in the ruleset we stick to a similar structure.

2024-11-21 07:15 UTC, AleksandarSavchev submitted a review, later dismissed
/lgtm

2024-11-21 12:07 UTC, dimityrmirchev requested changes
Just a few wording changes

2024-11-21 12:07 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006.go
> +		return rule.Result(r, rule.PassedCheckResult("Static token kubeconfig is locked to disabled for the shoot (Kubernetes version >= 1.27).", rule.NewTarget())), nil
```suggestion
		return rule.Result(r, rule.PassedCheckResult("Static token kubeconfig is locked to disabled (Kubernetes version >= 1.27).", rule.NewTarget())), nil
```

2024-11-21 12:07 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006.go
> +		return rule.Result(r, rule.PassedCheckResult("Static token kubeconfig is not enabled for the shoot.", rule.NewTarget())), nil
```suggestion
		return rule.Result(r, rule.PassedCheckResult("Static token kubeconfig is not enabled.", rule.NewTarget())), nil
```

2024-11-21 12:07 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006.go
> +		return rule.Result(r, rule.PassedCheckResult("Static token kubeconfig is disabled for the shoot.", rule.NewTarget())), nil
```suggestion
		return rule.Result(r, rule.PassedCheckResult("Static token kubeconfig is disabled.", rule.NewTarget())), nil
```

2024-11-21 12:07 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2006.go
> +	return rule.Result(r, rule.FailedCheckResult("Static token kubeconfig is enabled for the shoot.", rule.NewTarget())), nil
```suggestion
	return rule.Result(r, rule.FailedCheckResult("Static token kubeconfig is enabled.", rule.NewTarget())), nil
```

2024-11-21 12:35 UTC, dimityrmirchev approved these changes
/lgtm

2024-11-21 12:42 UTC, merged