[Security Hardened Shoot Cluster] Rule 2007 Implementation
gardener/diki pull request #374
Opened 2024-11-22 14:14 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR is an implementation of Rule 2007. It checks the PodSecurity admission plugin of the kube-apiserver and evaluates the restrictions it has, by comparing it to a maxmially allowed privilege that can be passed as an argument to the rule in the config file. By default it checks if the PodSecurity plugin is has a restriction of baseline or higher.

**Which issue(s) this PR fixes**:
Part of #304

**Special notes for your reviewer**:

**Release note**:

```feature user

```

2024-11-22 15:56 UTC, AleksandarSavchev requested changes
Thanks!

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go
> +		return err
```suggestion
		return fmt.Errorf("rule option 2007 error: %s", err.Error())
```

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	var podSecurityPlugin = "PodSecurity"
```suggestion
	var plugin = "PodSecurity"
```

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	enabledPodSecurityPluginIdx := slices.IndexFunc(shoot.Spec.Kubernetes.KubeAPIServer.AdmissionPlugins, func(admissionPlugin gardencorev1beta1.AdmissionPlugin) bool {
```suggestion
	pluginIdx := slices.IndexFunc(shoot.Spec.Kubernetes.KubeAPIServer.AdmissionPlugins, func(admissionPlugin gardencorev1beta1.AdmissionPlugin) bool {
```

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	r.Options.Validate()
```suggestion
```

We validate the option here:  https://github.com/gardener/diki/blob/913425ac0b004a11113024e60e36f5135565d2c9/pkg/provider/garden/ruleset/securityhardenedshoot/v01_ruleset.go#L118-L122

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	}
```suggestion
	if enabledPodSecurityPluginIdx < 0 || shoot.Spec.Kubernetes.KubeAPIServer.AdmissionPlugins[enabledPodSecurityPluginIdx].Config == nil {
		return rule.Result(r, rule.FailedCheckResult("PodSecurity admission plugin has a default security configuration.", rule.NewTarget())), nil
	}
```

These 2 cases should have the same message, since in both cases the `PodSecurity` plugin had been defaulted and enabled. ref https://github.com/gardener/gardener/blob/0b2f2a117b13f2c4e37bfd083e9a5b511e340071/pkg/utils/validation/admissionplugins/admissionplugins.go#L61

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	}
```suggestion
```

Remove if above suggestion is accepted

2024-11-22 15:56 UTC, AleksandarSavchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +		}
These 2 functions are now used in 2 rules(here and 254800). We can move them to the `pkg/internal/utils` package.

2024-11-22 15:58 UTC, AleksandarSavchev commented
Note. The example config should be updated with the new available options.

2024-11-25 09:17 UTC, dimityrmirchev requested changes
Thanks! I have several change requests that I think would be beneficial.

2024-11-25 09:17 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	if r.Options == nil {
Please do not mutate the rule struct, but rather initialize an option scoped to the rule's run. Also do this for rule 254800.

2024-11-25 09:17 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	var checkResults = []rule.CheckResult{}
```suggestion
	var checkResults []rule.CheckResult
```

2024-11-25 09:17 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	if utils.PrivilegeLevel(configuration.Defaults.Enforce) < utils.PrivilegeLevel(r.Options.MinPodSecurityLevel) {
You can use the new LessRestrictive function here.

2024-11-25 09:17 UTC, dimityrmirchev commented on pkg/shared/ruleset/disak8sstig/rules/254800.go
> +	"github.com/gardener/diki/pkg/internal/utils"
You can name the new import `intkubeutils`

2024-11-25 09:17 UTC, dimityrmirchev commented on example/config/garden.yaml
> +        minPodSecurityLevel: baseline
Should we comment this in order to note that this field is optional 🤔 
```suggestion
      # args:
      #   minPodSecurityStandardsProfile: baseline # if set it will indicate the min Pod Security Standards profile that is allowed. Possible values are "privileged", "baseline" and "restricted".  
```

2024-11-25 09:23 UTC, dimityrmirchev commented on example/config/garden.yaml
> +        minPodSecurityLevel: baseline
Now that I think of it we can comment out the whole rule.

2024-11-25 12:05 UTC, dimityrmirchev requested changes

2024-11-25 12:05 UTC, dimityrmirchev commented on pkg/provider/garden/ruleset/securityhardenedshoot/rules/2007.go
> +	}
```suggestion
options := cmp.Or(r.Options, &Options2007{MinPodSecurityStandardsProfile: "baseline"})
```

2024-11-25 12:05 UTC, dimityrmirchev commented on pkg/internal/utils/utils.go
> +// Level defines the order of restrictiveness of the differente PodSecurityStandardProfile values. Higher number indicates more restrictions.
```suggestion
// Level defines the order of restrictiveness of the different PodSecurityStandardProfile values. Higher number indicates more restrictions.
```

2024-11-25 12:05 UTC, dimityrmirchev commented on pkg/internal/utils/utils.go
> +type PodSecurityStandardProfile string
Please move this to a new package `pkg/internal/kubernetes/utils`

2024-11-25 13:13 UTC, dimityrmirchev submitted a review, later dismissed
Thanks!

/lgtm

2024-11-25 13:25 UTC, AleksandarSavchev approved these changes
/lgtm

2024-11-25 13:32 UTC, merged