[Security Hardened Kubernetes Cluster] Rule 2002 implementation
gardener/diki pull request #387
Opened 2024-11-28 09:18 UTC by georgibaltiev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part #356 

**Special notes for your reviewer**:

**Release note**:

```feature user
Implementation for rule `2002` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

2024-11-28 10:02 UTC, AleksandarSavchev requested changes
Thanks! There are some small changes, otherwise looks good.

2024-11-28 10:02 UTC, AleksandarSavchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2002_test.go
> +	)
```suggestion
	var (
		client            client.Client
		plainStorageClass *storagev1.StorageClass
		
		deleteReclaimPolicy    corev1.PersistentVolumeReclaimPolicy = "Delete"
		notDeleteReclaimPolicy corev1.PersistentVolumeReclaimPolicy = "NotDelete"

		ctx = context.TODO()
	)
```
I suggest we use these hard-coded policies in the units tests instead of `corev1.PersistentVolumeReclaimDelete` and `corev1.PersistentVolumeReclaimRetain`. So that we can catch when there are changes in upstream.

2024-11-28 13:51 UTC, dimityrmirchev requested changes
Just one request:

Storage classes are defaulted to have reclaim policy `Delete`. We should treat a `nil` reclaim policy as `Failed`.

2024-11-28 13:51 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2002.go
> +			checkResults = append(checkResults, rule.FailedCheckResult("StorageClass does not have a Delete ReclaimPolicy set.", rule.NewTarget("kind", "storageClass", "name", storageClass.Name)))
You can also extract the target as variable at the beginning of the loop.
```suggestion
		case storageClass.ReclaimPolicy != nil && *storageClass.ReclaimPolicy == corev1.PersistentVolumeReclaimDelete:
			checkResults = append(checkResults, rule.PassedCheckResult("StorageClass has a Delete ReclaimPolicy set.", target))
		default:
			checkResults = append(checkResults, rule.FailedCheckResult("StorageClass does not have a Delete ReclaimPolicy set.", target))
```

2024-11-28 14:43 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2002.go
> +			checkResults = append(checkResults, rule.FailedCheckResult("StorageClass does not have a configured ReclaimPolicy.", target))
No need for this case. We cover it in the dafault path

2024-11-29 06:41 UTC, dimityrmirchev approved these changes
/lgtm

2024-11-29 08:11 UTC, merged