[Security Hardened Kubernetes Cluster] Rule 2002 implementation
gardener/diki pull request #389
Opened 2024-11-28 14:42 UTC by georgibaltiev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #356 

**Special notes for your reviewer**:

**Release note**:

```feature user
Implementation for rule `2007` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

2024-11-28 15:13 UTC, AleksandarSavchev approved these changes
/lgtm

2024-11-29 06:44 UTC, dimityrmirchev requested changes
Just some minor requests

2024-11-29 06:44 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007.go
> +			msg := "RBAC Role is accepted to use \"*\" in policy rule verbs."
```suggestion
			msg := "Role is accepted to use \"*\" in policy rule verbs."
```

2024-11-29 06:44 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007.go
> +						}
```suggestion
						} 
							return rule.FailedCheckResult("Role uses \"*\" in policy rule verbs.", target)
						
```

2024-11-29 06:44 UTC, dimityrmirchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2007.go
> +			return rule.PassedCheckResult("RBAC Role does not use \"*\" in policy rule verbs.", target)
```suggestion
			return rule.PassedCheckResult("Role does not use \"*\" in policy rule verbs.", target)
```

2024-11-29 07:07 UTC, AleksandarSavchev requested changes
ClusterRoles are not namespaces

2024-11-29 07:07 UTC, AleksandarSavchev commented on example/config/managedk8s.yaml
> +    #       justification: "justification"
```suggestion
    #         foo: bar
    #       justification: "justification"
```

2024-11-29 07:07 UTC, AleksandarSavchev commented on example/config/managedk8s.yaml
> +    #       justification: "justification"
```suggestion
    #         foo: bar
    #       justification: "justification"
```

2024-11-29 07:08 UTC, AleksandarSavchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2006.go
> +						return rule.FailedCheckResult("RBAC Role uses \"*\" in policy rule resources.", target)
```suggestion
						return rule.FailedCheckResult("Role uses \"*\" in policy rule resources.", target)
```

2024-11-29 09:50 UTC, AleksandarSavchev approved these changes
/lgtm

2024-11-29 10:17 UTC, dimityrmirchev approved these changes
/lgtm

2024-11-29 10:17 UTC, merged