[Security Hardened Kubernetes Cluster] Rule 2003 implementation
gardener/diki pull request #391
Opened 2024-12-02 07:17 UTC by georgibaltiev

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Part of #356 

**Special notes for your reviewer**:

**Release note**:

```feature user
Implementation for rule `2003` from the `security-hardened-k8s` ruleset for provider `managedk8s`.
```

2024-12-02 10:53 UTC, AleksandarSavchev requested changes
Please update example config with new option.

2024-12-02 13:10 UTC, georgibaltiev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003.go
> +				volume.Ephemeral == nil && volume.PersistentVolumeClaim == nil && volume.Projected == nil && volume.Secret == nil {
Should I leave it as it is, or should I reverse the check to look for each of the volume types individually?

2024-12-02 13:15 UTC, AleksandarSavchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2003.go
> +				volume.Ephemeral == nil && volume.PersistentVolumeClaim == nil && volume.Projected == nil && volume.Secret == nil {
Let's leave the check as it is. The only improvement we can do is to spread the check in more lines, to be easily readible.

2024-12-09 12:58 UTC, AleksandarSavchev approved these changes
/lgtm

2024-12-09 12:58 UTC, merged