Refactor Rules that can potentially return empty CheckResults to handle their edge cases.
gardener/diki pull request #413
Opened 2024-12-23 13:24 UTC by georgibaltiev

**What this PR does / why we need it**:
This PR refactors rules that could return empty check results when no resources (pods, services, containers, etc.) are present for evaluation in the target. 

The following list contains the known rules that are susceptible to this issue:

- [ ] Rule 2003 of the Security Hardened Kubernetes ruleset
- [ ] Rule 2004 of the Security Hardened Kubernetes ruleset
- [ ] Rule 2005 of the Security Hardened Kubernetes ruleset
- [ ] Rule 2008 of the Security Hardened Kubernetes ruleset
- [ ] Rule 242415 of the DISA Kubernetes STIG ruleset for the Managed Kubernetes provider

**Which issue(s) this PR fixes**:
Fixes #408 

**Special notes for your reviewer**:
More rules may be added to this list if they appear to exhibit the same behaviour

**Release note**:

```feature user

```

2025-01-10 15:32 UTC, AleksandarSavchev requested changes
Thanks, I added 3 more rules in the PR description that I think should be improved.

2025-01-10 15:32 UTC, AleksandarSavchev commented on pkg/provider/managedk8s/ruleset/disak8sstig/rules/242415.go
> +		return rule.Result(r, rule.PassedCheckResult("There are no pods to be evaluated.", target)), nil
```suggestion
		return rule.Result(r, rule.PassedCheckResult("The cluster does not have any Pods.", target)), nil
```
Let's use a similar message to the one used in rule 2002. [ref](https://github.com/gardener/diki/blob/8e2d4e195f80b014997bece5e5f0bf908e7c82ed/pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2002.go#L46)

Modify the message in all other occurrences in this PR.

2025-01-10 15:32 UTC, AleksandarSavchev commented on pkg/provider/managedk8s/ruleset/securityhardenedk8s/rules/2005.go
> +
```suggestion
```
It is not possible to create a pod without a single container. This check is not needed.

2025-01-10 15:32 UTC, AleksandarSavchev commented on pkg/shared/ruleset/ruleset.go
> +					res.CheckResults = append(res.CheckResults, rule.ErroredCheckResult("Undefined - No check results are present.", rule.NewTarget()))
```suggestion
					res.CheckResults = append(res.CheckResults, rule.ErroredCheckResult("rule run did not report any status", rule.NewTarget()))
```

2025-01-14 08:01 UTC, AleksandarSavchev requested changes
One final nit, otherwise looks good.

2025-01-14 08:06 UTC, georgibaltiev commented on pkg/shared/ruleset/disak8sstig/rules/242404_test.go
> +var _ = Describe("#242404", func() {
I wanted to avoid refactoring the original test cases as much as possible, but I will move it because the required changes do not amount to much.

2025-01-14 09:53 UTC, AleksandarSavchev submitted a review, later dismissed
/lgtm

2025-01-14 13:16 UTC, dimityrmirchev commented on pkg/shared/ruleset/ruleset.go
> +				}
To be honest I think that this should not be here as the error is not actually reported by a rule run.

2025-01-14 14:38 UTC, georgibaltiev commented on pkg/shared/ruleset/ruleset.go
> +				}
I've amended the checkResult to be of a Warning status. This safeguard is added in order to prevent any future rules that may exhibit the same behaviour.

2025-01-14 14:40 UTC, dimityrmirchev approved these changes
/lgtm

2025-01-14 14:47 UTC, merged