[Kubernetes STIG v1r10] pod-files rule: add check for 242467 rule
gardener/diki pull request #60
Opened 2023-10-24 13:19 UTC by AleksandarSavchev

**What this PR does / why we need it**:
This PR improves the *.key files checks required from `242467` rule in `pod-files` rule. *.key files in mandatory components are required to have max privilege of `600`.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```bugfix user
DISA Kubernetes STIGs `pod-files` rule now correctly checks `*.key` files in mandatory components as  suggested in `242467` rule.
```

2023-11-20 12:21 UTC, dimityrmirchev requested changes
Some minor requests from my side

2023-11-20 12:21 UTC, dimityrmirchev commented on pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
> +	Num   int
Let's remove the Num field and again use a `map[string]component`

2023-11-20 12:21 UTC, dimityrmirchev commented on pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner_test.go
> +		keyFileStats = `600 0 0 /destination/file1.key
```suggestion
		keyFileStats = `640 0 0 /destination/file1.key
```

2023-11-20 12:33 UTC, AleksandarSavchev commented on pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
> +	Num   int
We cannot use the old method of removing a found component from the map, since a mandatory component can have more than 1 pod and we want to make the `key` file checks for every single pod of that component. Using the old logic we would know only for the first pod of the component that we need to check the `key` files.

I suggest I change the `Num int` filed to `Found bool`

2023-11-20 13:06 UTC, dimityrmirchev commented on pkg/provider/gardener/ruleset/disak8sstig/v1r10/pod_files_permissions_and_owner.go
> +	Num   int
Ok then. Lets change "Num" to "found"

2023-11-21 08:14 UTC, dimityrmirchev approved these changes
/lgtm

2023-11-21 08:32 UTC, merged